### ISSUE TITLE
Cannot use custom effdirs.

### ISSUE THREAD

**Issue by Galaxy5151** [Emd4600/SporeModder-FX#1]
I don't know if this is just me being stupid, but for some reason, I can't use custom effdirs for modified effects.

**Comment by Emd4600** [comment]
Custom effdirs have to be placed into the ep1_effects_3~ folder in order to
work. Sorry there is not a tutorial for that 😅

By the way, if you have a Discord account you could join the Spore server.
There are other modders there as well.
