### ISSUE TITLE
Effect creation and fading by camera angle doesn't unpack or pack correctly

### ISSUE THREAD

**Issue by Splitwirez** [emd4600/SporeModder-FX#11]
While trying to transfer some of my effects from OG SporeModder to SporeModder FX, I noticed something odd: All of the effects which used a camera angle-based fade-out (like the Land Vehicle Editor background's pedestal when the camera pivots below ground level) had ceased to function. At first I suspected that transferring over my existing PFX files (made for OG SporeModder) was the issue, so I tried packing them with OG SporeModder one last time, and then unpacking them with SporeModder FX, but this didn't help at all.

At this point, I decided to take a look at some of the unpacked Core Spore effects - surely those should demonstrate how to correctly do this in SporeModder FX, right? Wrong. The value for `extendedLodWeights` seemed incorrect - it was `0 0 0`, whereas the exact same effect unpacked with OG SporeModder yielded `(0.0, 1.0, 0.0)`. Another discrepancy I noticed was that with SporeModder FX, `-emitScale` and `-sizeScale` options were present on the `particles` effect within the affected effect, both with a series of `1` values, one for each `lodDistances` value present, but both of these options were completely absent from OG SporeModder's unpacked PFX file.

I need to be able to create effects which use this behaviour, and until SporeModder FX can do that for me, I can't completely migrate to it.

Here's one of my effects which was affected by the issue:
[DI9r_heroEditor_skinMode_enter.pfx](https://cdn.discordapp.com/attachments/332600164307173387/624372775649542148/DI9r_heroEditor_skinMode_enter.pfx)
To avoid ambiguity, I will note that this PFX file is intended for OG SporeModder. I would have provided the SMFX version, but I'm not 100% sure what that is meant to even look like, hence my initial hesitance to even bring this issue up.

And as requested, here's an example of a base game effect which is affected, unpacked using SporeModder FX:
[0xDD5D44DE.pfx](https://cdn.discordapp.com/attachments/332600164307173387/624943656574517259/0xDD5D44DE.pfx)

**Comment by emd4600** [comment]
Fixed along with #38.
