### ISSUE TITLE
Repacked unmodified .package file will have bigger size than the original file

### ISSUE THREAD

**Issue by Radu13** [emd4600/SporeModder-FX#27]
As title said unpacking and repacking for example `BP2_Data.package` (bot parts original file) with size of `3997 KB` will return a new package with size of `8988 KB`.
Opening both on HxD I noticed the new one isn't encrypted as well, so I wonder if you are aware of this or not?
![unknownPKG](https://user-images.githubusercontent.com/25487544/82154926-73d09f80-9871-11ea-93e5-78b02ff2c12a.png)

**Comment by emd4600** [comment]
Spore sometimes compresses files inside the packages. For now this feature won't be added to SMFX.
