### ISSUE TITLE
Import Folder

### ISSUE THREAD

**Issue by vaportropicae** [Emd4600/SporeModder-FX#3]
Is there a way to import a folder with files inside?

Ex: Import Spacetools~ folder from another unpacked mod file.

**Comment by Emd4600** [comment]
In the **Project Settings** you can add one or more projects to be the `source` of the current mod. This way, the files of those projects will appear in the Project tree, and you can import the folder you want to your mod using the **Modify** button.

![](https://i.imgur.com/00YUKL9.png)

**Comment by vaportropicae** [comment]
Thanks, man.
