### ISSUE TITLE
SporeModder-FX is not unpacking presets.

### ISSUE THREAD

**Issue by CebbyS** [emd4600/SporeModder-FX#31]
Whenever I try to unpack presets ( Spore (Gameplay & Graphics) &|| Spore Music &|| Player Creations ) loading gets stuck at `Clearing folder` and does not go further. I kept the process going for 3 hours but still no progress. Is there a way to clear cache or some config files to reset the SporeModder. Because I have tried to delete and redownload the modder, but still whenever I open the launcher it has the old configuration.
![image](https://user-images.githubusercontent.com/56877579/91592577-6a260000-e967-11ea-9608-fa6252f21911.png)

**Comment by emd4600** [comment]
I've updated SporeModder FX with a fix with this issue. Could you please try if it still happens? (when you open the program, ensure it says `v2.1.21` on the title)

**Comment by CebbyS** [comment]
Thank you!

I can confirm that after the update the bug is gone and now files are being
unpacked!

Best regards, Cebbys!

otrd., 2020. g. 8. sept., plkst. 00:15 — lietotājs Eric Mor (<
notifications@github.com>) rakstīja:

**Comment by CebbyS** [comment]
Update fixed file clearing bug.
