### ISSUE TITLE
Fails to unpack Ep1_PatchData data and PatchData

### ISSUE THREAD

**Issue by CebbyS** [emd4600/SporeModder-FX#32]
![image](https://user-images.githubusercontent.com/56877579/92629387-ebba4e00-f2d6-11ea-8a03-30026a205ac6.png)

When trying to unpack spore data this happens. Using Origin Spore. Both spore paths lead to correct folders.

![image](https://user-images.githubusercontent.com/56877579/92629635-48b60400-f2d7-11ea-9790-0d2bf3751220.png)

What could be the issue?

**Comment by emd4600** [comment]
If I remember correctly, Origin doesn't have those files. But don't worry, I guess everything they had is in the other packages.
