### ISSUE TITLE
Effect flags for editor pedestal fade-out by camera rotation fails when repacking

### ISSUE THREAD

**Issue by Splitwirez** [emd4600/SporeModder-FX#38]
The `-flags` option on an effect either doesn't work at all, or at least fails for the specific set of flags (`0x80000`) used by the vehicle editors' pedestal effects. This is used in vanilla to cause the pedestal to fade out when the camera pivots to a position below it, and I need it in order to finish moving Dark Injection to SporeModder FX.

An example of one such effect can be seen in the base game at `gameEffects_3~!editors.effdir`, `0xDD5D44DE.pfx` (which is the pedestal for the land vehicle editor), on line 52.

**Comment by emd4600** [comment]
The problem wasn't actually the flags, but the `-extendedLodWeights` option, which was being both packed and unpacked incorrectly.
