### ISSUE TITLE
Two different Group IDs have the same alias

### ISSUE THREAD

**Issue by VanillaCold** [emd4600/SporeModder-FX#54]
Both `0xE38475D9` and `0x4084b000` use the `PlanetScripts` alias, except with different capitalization.
Windows doesn't support having multiple files with the same name but different capitalization, so they get merged into the same folder and only one of the two is packed.

**Comment by 0KepOnline** [comment]
This bug will be (partially) fixed in the next SporeModder FX version. `0xE38475D9` will be renamed as `StarterWorlds`.
